<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Amber Horbath" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 2</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2/">Project 2</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          May 13, 2020
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="r-markdown" class="section level2">
<h2>R Markdown</h2>
<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com" class="uri">http://rmarkdown.rstudio.com</a>.</p>
<p>When you click the <strong>Knit</strong> button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:</p>
<pre class="r"><code>library(robustbase)
head(CrohnD)</code></pre>
<pre><code>##      ID nrAdvE   BMI height country sex age weight   treat
## 1 19908      4 25.22    163      c1   F  47     67 placebo
## 2 19909      4 23.80    164      c1   F  53     64      d1
## 3 19910      1 23.05    164      c1   F  68     62 placebo
## 4 20908      1 25.71    165      c1   F  48     70      d2
## 5 20909      2 25.95    170      c1   F  67     75 placebo
## 6 20910      2 28.70    168      c1   F  54     81      d1</code></pre>
</div>
<div id="this-data-set-contains-the-results-of-117-patients-with-crohns-disease-that-were-given-a-treatment-placebo-drug-1-or-drug-2.-the-independent-variable-is-the-number-of-adverse-events-side-effects-while-on-the-given-treatment.-there-are-9-variables-patient-id-the-number-of-adverse-events-while-on-treatment-drug-nradve-bmi-weightkgheightm2-height-cm-the-country-that-the-patient-lives-in-c1-or-c2-the-sex-of-the-patient-the-age-of-the-patient-the-patients-weight-kg-and-the-given-treatment-for-each-patient-placebo-drug-1-or-drug-2.-there-are-117-observations-in-the-data-set." class="section level2">
<h2>This data set contains the results of 117 patients with Crohn’s disease that were given a treatment (placebo, drug 1, or drug 2). The independent variable is the number of adverse events (side effects) while on the given treatment. There are 9 variables: patient ID, the number of adverse events while on treatment drug (nrAdvE), BMI (weight[kg]/height[m]^2), height (cm), the country that the patient lives in (c1 or c2), the sex of the patient, the age of the patient, the patient’s weight (kg), and the given treatment for each patient (placebo, drug 1, or drug 2). There are 117 observations in the data set.</h2>
<pre class="r"><code>##ASSUMPTIONS

#density plots for multivariate normality 
library(ggplot2)
ggplot(CrohnD, aes(weight, height)) + geom_point(alpha = .5) +
         geom_density_2d(h=2) + coord_fixed() + facet_wrap(~sex)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>##Box&#39;s M-test for Homogeneity of Covariance Matrices
library(heplots)</code></pre>
<pre><code>## Loading required package: car</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre class="r"><code>res &lt;- boxM(cbind(weight, height) ~ sex, data=CrohnD)
res</code></pre>
<pre><code>## 
##  Box&#39;s M-test for Homogeneity of Covariance Matrices
## 
## data:  Y
## Chi-Sq (approx.) = 37.694, df = 3, p-value = 3.282e-08</code></pre>
<pre class="r"><code>##MANOVA test - to test if height and weight differ between males and females with Crohn&#39;s disease
man1&lt;-manova(cbind(weight, height)~sex, data=CrohnD)
summary(man1)</code></pre>
<pre><code>##            Df  Pillai approx F num Df den Df    Pr(&gt;F)    
## sex         1 0.23453   17.463      2    114 2.421e-07 ***
## Residuals 115                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>##univariate ANOVAs
summary.aov(man1)</code></pre>
<pre><code>##  Response weight :
##              Df  Sum Sq Mean Sq F value   Pr(&gt;F)   
## sex           1  2121.3 2121.33  11.392 0.001006 **
## Residuals   115 21413.6  186.21                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response height :
##              Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## sex           1 2028.2 2028.19  33.687 5.829e-08 ***
## Residuals   115 6923.8   60.21                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>## post-hoc pair-wise t-tests
library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ tibble  3.0.1     ✓ dplyr   0.8.5
## ✓ tidyr   1.0.3     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.5.0
## ✓ purrr   0.3.4</code></pre>
<pre><code>## ── Conflicts ───────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## x dplyr::recode() masks car::recode()
## x purrr::some()   masks car::some()</code></pre>
<pre class="r"><code>CrohnD%&gt;%group_by(sex)%&gt;%summarize(mean(BMI),mean(nrAdvE),mean(height),mean(weight))</code></pre>
<pre><code>## # A tibble: 2 x 5
##   sex   `mean(BMI)` `mean(nrAdvE)` `mean(height)` `mean(weight)`
##   &lt;fct&gt;       &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
## 1 M            27.0           2.71           173.           79.4
## 2 F            25.9           1.92           161.           67.3</code></pre>
<pre class="r"><code>pairwise.t.test(CrohnD$height,CrohnD$sex, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  CrohnD$height and CrohnD$sex 
## 
##   M      
## F 5.8e-08
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(CrohnD$weight,CrohnD$sex, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  CrohnD$weight and CrohnD$sex 
## 
##   M    
## F 0.001
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#ran 1 MANOVA test, 2 univariate ANOVAs, and 2 pair-wise t-tests, 1 box M-test = 6 tests
# alpha = .05/7 = .00833
# probability of at least 1 type-I error: 1-(0.95^6) = 0.265</code></pre>
<p><em>A one-way MANOVA was conducted to determine the effect of the patients’ gender (male or female) on two dependent variables (height and weight of patients). The bivariate density plots for each group showed more of an ovoid shape for the points of both male and female with several outliers in both plots. Therefore, the assumption for multivariate normality was not met. For the homogeneity of covariances assumption I ran Box’s M-test which resulted in a p-value of 3.282E-8. Therefore, I can reject the null hypothesis that the observed covariance matrices of the dependent variables (weight and height) are equal across both genders of the patients and the assumption for homogeneity of covariances is met. When I ran the MANOVA, I found that significant differences were found between genders of the patients for at least one of the dependent variables (weight or height) with a p-value of 2.421E-7 (Pillai trace = 0.23453, F-statistic = 17.463, p&lt;0.0001). Univariate ANOVAs for each dependent variable were conducted using the Bonferroni method to control the Type I error rate. Only the univariate ANOVA for height was significant with an alpha of 0.0001 (p-value = 5.829E-8, F-statistic = 33.687). The univariate ANOVA for weight was not significant with alpha=0.0001 (p-value = 0.001, F-statistic = 11.392). However, with the bonferroni adjusted alpha of 0.00833 both variables were significant. Post-hoc analysis was performed conducting pairwise t-tests to determine which gender differed in patient weight and height. Both sexes were found to differ significantly from each other in terms of patient height and weight after adjusting for multiple comparisons (bonferroni alpha = 0.05/6 = 0.00833). There were 6 tests performed (1 MANOVA, 2 univariate ANOVAs, 2 pair-wise t-tests, and 1 box M-test) and the probability of at least one Type I error is 1-(0.95^6) = 0.265.</em></p>
<pre class="r"><code>##randomization test

##to get F-statistic
summary(aov(nrAdvE~country,data=CrohnD))</code></pre>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)  
## country       1   21.5  21.543   2.941  0.089 .
## Residuals   115  842.3   7.325                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>obs_F&lt;-2.941
Fs&lt;-replicate(5000,{ 
new&lt;-CrohnD%&gt;%mutate(nrAdvE=sample(nrAdvE)) 

SSW&lt;- new%&gt;%group_by(country)%&gt;%summarize(SSW=sum((nrAdvE-mean(nrAdvE))^2))%&gt;%
summarize(sum(SSW))%&gt;%pull
SSB&lt;- new%&gt;%mutate(mean=mean(nrAdvE))%&gt;%group_by(country)%&gt;%mutate(groupmean=mean(nrAdvE))%&gt;%
summarize(SSB=sum((mean-groupmean)^2))%&gt;%summarize(sum(SSB))%&gt;%pull
(SSB/1)/(SSW/115) #F-statistic = 41.281
})

hist(Fs, prob=T); abline(v = obs_F, col=&quot;red&quot;,add=T)</code></pre>
<pre><code>## Warning in int_abline(a = a, b = b, h = h, v = v, untf = untf, ...): &quot;add&quot; is
## not a graphical parameter</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>mean(Fs&gt;obs_F) #p-value is 0.0876</code></pre>
<pre><code>## [1] 0.0862</code></pre>
<p><em>H0 = There is no significant mean difference between the groups.</em>
<em>HA = There is a significant mean difference between the groups.</em>
<em>After performing the randomization test, we get a p-value of 0.0876 (p-value &lt; alpha(0.05) ) which means that we fail to reject the null-hypothesis and can conclude that there is no signifcant mean difference between the groups (number of adverse events and the country that the patient resides in). Not all of the 5000 F-statistics generated under the null hypothesis were bigger than our actual F statistic (2.941).</em></p>
<pre class="r"><code>library(sandwich);library(lmtest)</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>fit&lt;-lm(nrAdvE ~ age*weight, data=CrohnD) #Regression before centering
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = nrAdvE ~ age * weight, data = CrohnD)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.238 -1.902 -1.095  1.038 10.052 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 10.181971   7.263826   1.402    0.164
## age         -0.159017   0.133936  -1.187    0.238
## weight      -0.150109   0.111470  -1.347    0.181
## age:weight   0.002889   0.002056   1.405    0.163
## 
## Residual standard error: 2.726 on 113 degrees of freedom
## Multiple R-squared:  0.02805,    Adjusted R-squared:  0.002251 
## F-statistic: 1.087 on 3 and 113 DF,  p-value: 0.3576</code></pre>
<pre class="r"><code>CrohnD$weight_c &lt;- CrohnD$weight - mean(CrohnD$weight)
CrohnD$age_c &lt;- CrohnD$age - mean(CrohnD$age)
fit_c&lt;-lm(nrAdvE ~ age_c*weight_c, data=CrohnD)
summary(fit_c)</code></pre>
<pre><code>## 
## Call:
## lm(formula = nrAdvE ~ age_c * weight_c, data = CrohnD)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.238 -1.902 -1.095  1.038 10.052 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    2.029520   0.252028   8.053 9.09e-13 ***
## age_c          0.040413   0.025801   1.566    0.120    
## weight_c       0.007811   0.017925   0.436    0.664    
## age_c:weight_c 0.002889   0.002056   1.405    0.163    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.726 on 113 degrees of freedom
## Multiple R-squared:  0.02805,    Adjusted R-squared:  0.002251 
## F-statistic: 1.087 on 3 and 113 DF,  p-value: 0.3576</code></pre>
<pre class="r"><code>new1&lt;-CrohnD
new1$weight_c&lt;-mean(CrohnD$weight_c)
new1$mean&lt;-predict(fit_c,new1)
new1$weight_c&lt;-mean(CrohnD$weight_c)+sd(CrohnD$weight_c)
new1$plus.sd&lt;-predict(fit_c,new1)
new1$weight_c&lt;-mean(CrohnD$weight_c)-sd(CrohnD$weight_c)
new1$minus.sd&lt;-predict(fit_c,new1)
newint&lt;-new1%&gt;%select(nrAdvE,age_c,mean,plus.sd,minus.sd)%&gt;%gather(weight_c,value,-nrAdvE,-age_c)

mycols&lt;-c(&quot;#619CFF&quot;,&quot;#F8766D&quot;,&quot;#00BA38&quot;)
names(mycols)&lt;-c(&quot;-1 sd&quot;,&quot;mean&quot;,&quot;+1 sd&quot;)
mycols=as.factor(mycols)


##Interaction Plot
ggplot(CrohnD,aes(age_c,nrAdvE),group=mycols)+geom_point()+geom_line(data=new1,aes(y=mean,color=&quot;mean&quot;))+geom_line(data=new1,aes(y=plus.sd,color=&quot;+1 sd&quot;))+geom_line(data=new1,aes(y=minus.sd,color=&quot;-1 sd&quot;))+scale_color_manual(values=mycols)+labs(color=&quot;weight (cont)&quot;)+theme(legend.position=c(.9,.2))</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>##ASSUMPTIONS
##Linearity/Homoskedasticity
resids &lt;- fit_c$residuals
fitvals&lt;-fit_c$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;green&#39;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre class="r"><code>##Normality
ks.test(resids, &quot;pnorm&quot;, mean=0, sd(resids)) ## H0: true distribution is normal, p-value = 0.0003672</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.19174, p-value = 0.0003672
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code>##regression with robust standard errors
summary(fit_c)$coef[,1:2] #uncorrected SEs</code></pre>
<pre><code>##                   Estimate  Std. Error
## (Intercept)    2.029520198 0.252028123
## age_c          0.040412874 0.025801323
## weight_c       0.007810769 0.017924804
## age_c:weight_c 0.002889221 0.002056411</code></pre>
<pre class="r"><code>coeftest(fit_c, vcov = vcovHC(fit_c))[,1:2] #corrected SEs</code></pre>
<pre><code>##                   Estimate  Std. Error
## (Intercept)    2.029520198 0.256652387
## age_c          0.040412874 0.025426486
## weight_c       0.007810769 0.017594426
## age_c:weight_c 0.002889221 0.002816447</code></pre>
<p><em>Interpretations of coeffiecients - Intercept: The predicted number of adverse events for an average weight and age of a patient is 2.02952. Age: Patients show an increase of 0.040413 adverse events for every 1 year increase in age, on average. Weight: Patients show an increase of 0.007811 adverse events for every one kg increase in weight, on average. Age:Weight interaction: The difference in slope for the number of adverse events is 0.002889 for age and weight of the patients. The assumptions for linearity and homoskedasticity were checked by plotting the residuals of the model. The plot of the residuals looks very ‘iffy.’ On one hand, the points at the top of the plot show a pretty even spread with no real pattern, but towards the bottom of the plot, there is an obvious trend occurring. Therefore, the assumptions for linearity and homoskedasticity are not met. When checking the normality assumption, I ran the one-sample Kolmogorov-Smirnov test which resulted in a p-value of 0.0003672. The null hypothesis for the test is that the true distribution is normal and since we have a p-value that is less than 0.05, we reject the null and the normality assumption is not met. After recomputing the regression with robust standard errors, the new resulting standard errors are greater and this is because it is accounting for the penalty for not meeting the homoskedasticity assumption. Because the R^2 value is 0.02805, we can say that 2.805% of the variation is explained by the model.</em></p>
<pre class="r"><code>##Bootstrapped SEs

samp_distn&lt;-replicate(5000, {
boot_dat&lt;-boot_dat&lt;-CrohnD[sample(nrow(CrohnD),replace=TRUE),]
fit2&lt;-lm(nrAdvE ~ age_c * weight_c, data=boot_dat)
coef(fit2)
})

## Estimated SEs
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)      age_c   weight_c age_c:weight_c
## 1    0.247677 0.02527737 0.01719074    0.002454261</code></pre>
<pre class="r"><code>###COMPARE</code></pre>
<p><em>Comparing the standard errors from the original model, the bootstrapped standard errors, and the robust standard errors, the original model had the smallest standard errors, the robust standard errors were the greatest, and the bootstrapped standard errors were in between.</em></p>
<pre class="r"><code>library(glmnet)</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 3.0-2</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
prediction&lt;-ifelse(probs&gt;.5,1,0)
acc=mean(truth==prediction)
sens=mean(prediction[truth==1]==1)
spec=mean(prediction[truth==0]==0)
ppv=mean(truth[prediction==1]==1)
#CALCULATE EXACT AUC
ord&lt;-order(probs, decreasing=TRUE)
probs &lt;- probs[ord]; truth &lt;- truth[ord]
TPR=cumsum(truth)/max(1,sum(truth))
FPR=cumsum(!truth)/max(1,sum(!truth))
dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
n &lt;- length(TPR)
auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
data.frame(acc,sens,spec,ppv,auc)
}


#Logistic regression
log_fit &lt;- glm(country ~ age + treat, data = CrohnD, family = &quot;binomial&quot;)
summary(log_fit)</code></pre>
<pre><code>## 
## Call:
## glm(formula = country ~ age + treat, family = &quot;binomial&quot;, data = CrohnD)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.2886  -0.9116  -0.7856   1.2930   1.9418  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept) -3.23246    1.27322  -2.539   0.0111 *
## age          0.04396    0.02095   2.099   0.0358 *
## treatd1      0.10717    0.49229   0.218   0.8277  
## treatd2      0.19283    0.49864   0.387   0.6990  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 148.94  on 116  degrees of freedom
## Residual deviance: 144.11  on 113  degrees of freedom
## AIC: 152.11
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>exp(coef(log_fit))</code></pre>
<pre><code>## (Intercept)         age     treatd1     treatd2 
##  0.03946039  1.04494320  1.11312747  1.21267335</code></pre>
<pre class="r"><code>prob&lt;-predict(log_fit,type=&quot;response&quot;)
pred&lt;-ifelse(prob&gt;.5,1,0)
table(prediction=pred, truth=CrohnD$country)%&gt;%addmargins</code></pre>
<pre><code>##           truth
## prediction  c1  c2 Sum
##        0    76  37 113
##        1     2   2   4
##        Sum  78  39 117</code></pre>
<pre class="r"><code>(76+2)/117 #accuracy</code></pre>
<pre><code>## [1] 0.6666667</code></pre>
<pre class="r"><code>2/39 #sensitivity (TPR)</code></pre>
<pre><code>## [1] 0.05128205</code></pre>
<pre class="r"><code>76/78 #specificity (TNR)</code></pre>
<pre><code>## [1] 0.974359</code></pre>
<pre class="r"><code>2/4 #precision (PPV)</code></pre>
<pre><code>## [1] 0.5</code></pre>
<pre class="r"><code>CrohnD$logit&lt;-predict(log_fit,type=&quot;link&quot;) #log-odds

## Density plot of log-odds for both countries:

CrohnD%&gt;%ggplot()+geom_density(aes(logit,color=country,fill=country), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)+
  geom_rug(aes(logit,color=country))+
  geom_text(x=-5,y=.07,label=&quot;TN = 431&quot;)+
  geom_text(x=-1.75,y=.008,label=&quot;FN = 19&quot;)+
  geom_text(x=1,y=.006,label=&quot;FP = 13&quot;)+
  geom_text(x=5,y=.04,label=&quot;TP = 220&quot;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>##ROC plot
library(plotROC)
ROCplot&lt;-ggplot(CrohnD)+geom_roc(aes(d=country,m=prob), n.cuts=0) 
ROCplot</code></pre>
<pre><code>## Warning in verify_d(data$d): D not labeled 0/1, assuming c1 = 0 and c2 = 1!</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<pre class="r"><code>calc_auc(ROCplot) #AUC = 0.6382314</code></pre>
<pre><code>## Warning in verify_d(data$d): D not labeled 0/1, assuming c1 = 0 and c2 = 1!</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.6382314</code></pre>
<pre class="r"><code>#10-fold CV
set.seed(1234)
k=10 

data&lt;-CrohnD[sample(nrow(CrohnD)),] 
folds&lt;-cut(seq(1:nrow(CrohnD)),breaks=k,labels=F) 

diags&lt;-NULL
for(i in 1:k){

  train&lt;-data[folds!=i,] 
  test&lt;-data[folds==i,]
  
  truth&lt;-test$country
  
  
  fit3&lt;-glm(country~age+treat,data=train,family=&quot;binomial&quot;)
  
 
  probs&lt;-predict(fit3,newdata = test,type=&quot;response&quot;)
  
  
  diags&lt;-rbind(diags,class_diag(probs,truth))
}


summarize_all(diags,mean)</code></pre>
<pre><code>##         acc sens      spec ppv       auc
## 1 0.6227273    0 0.9305556 NaN 0.5749627</code></pre>
<p><em>Interpretation of coefficients - Intercept: The odds of being from country 2 and under the placebo treatment, age = 0 is -3.23246. Age: Controlling for treatment type, for every 1 year increase in the patient’s age, the odds of being from country 2 increases by a factor of 0.04396. Treatment 1: Controlling for age, odds of being from country 2 and under treatment 1 is 0.10717 times greater than the odds of being from country 2 when under the placebo treatment. Treatment 2: Controlling for age, the odds of being from country 2 and under treatment 2 is 0.19283 times greater than the odds of being from country 2 and under the placebo treatment. The accuracy of this model is 0.667 which means that only 66.7% of the patients are being correctly predicted in terms of what country they live in. The sensitivity or the true positive rate is 0.0512 which means that there is a 5.12% chance of predicting that the patient is from country 2 when that is actually where they are from. The specificity or the true negative rate is 0.9744 which means that there is a 97.44% chance of predicting that a patient is from country 2 when they are actually from country 1. The precision is 0.5 which means that only 50% of the patients who live in country 2 are being classified as such. The AUC which summarizes both the specificity and the sensitivity of the logistic regression calculated from the ROC plot is 0.6382314 which is categorized as poor. After the 10-fold cross validation, the out-of-sample accuracy is now 0.6576, the sensitivity increased to 0.0533, and the specificity decreased to 0.955 with an even worse AUC of 0.5246.</em></p>
<pre class="r"><code>##LASSO regression
y &lt;- as.matrix(CrohnD$sex)
x &lt;- model.matrix(sex~ -1+., data=CrohnD)
head(x)</code></pre>
<pre><code>##      ID nrAdvE   BMI height countryc1 countryc2 age weight treatd1 treatd2
## 1 19908      4 25.22    163         1         0  47     67       0       0
## 2 19909      4 23.80    164         1         0  53     64       1       0
## 3 19910      1 23.05    164         1         0  68     62       0       0
## 4 20908      1 25.71    165         1         0  48     70       0       1
## 5 20909      2 25.95    170         1         0  67     75       0       0
## 6 20910      2 28.70    168         1         0  54     81       1       0
##    weight_c      age_c      logit
## 1 -2.025641 -7.6581197 -1.1662188
## 2 -5.025641 -1.6581197 -0.7952700
## 3 -7.025641 13.3418803 -0.2430057
## 4  0.974359 -6.6581197 -0.9294290
## 5  5.974359 12.3418803 -0.2869682
## 6 11.974359 -0.6581197 -0.7513075</code></pre>
<pre class="r"><code>set.seed(1234)
cv&lt;-cv.glmnet(x,y,family=&#39;binomial&#39;)
lasso&lt;-glmnet(x,y,family=&#39;binomial&#39;,lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 14 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                      s0
## (Intercept) -9.91195106
## ID           .         
## nrAdvE       .         
## BMI          .         
## height       0.04964553
## countryc1    .         
## countryc2    .         
## age          .         
## weight       .         
## treatd1      .         
## treatd2      .         
## weight_c     .         
## age_c        .         
## logit        .</code></pre>
<pre class="r"><code>#cross-validating lasso model
set.seed(1234)
k=10 
data1&lt;-CrohnD[sample(nrow(CrohnD)),] 
folds&lt;-cut(seq(1:nrow(CrohnD)),breaks=k,labels=F) 
diags&lt;-NULL
for(i in 1:k){

train&lt;-data1[folds!=i,]
test&lt;-data1[folds==i,]
truth&lt;-test$sex

fit_l&lt;-glm(sex~.,data=train,family=&quot;binomial&quot;)
probs&lt;-predict(fit_l,newdata = test,type=&quot;response&quot;)

diags&lt;-rbind(diags,class_diag(probs,truth))
}</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading

## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading

## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading

## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading

## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading

## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading

## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading</code></pre>
<pre class="r"><code>diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##         acc sens spec       ppv       auc
## 1 0.8901515 0.94  NaN 0.9352273 0.9250649</code></pre>
<p><em>Lasso regression - sex of patients tested against all other predictors. The only variable that was retained after performing the lasso regression is height. Therefore, height is the most predictive variable of the patients’ sex (makes sense!). A 10-fold cross validation was performed on the model and the AUC is 0.8247 (in the “Good” range) which is much better than the AUC from the previous 10-fold cross validation.</em></p>
</div>

              <hr>
              <div class="related-posts">
                <h5></h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
